openapi: 3.0.0
info:
  title: ShareHub Settings API
  version: 1.0.0
  description: Tenant settings management endpoints

paths:
  /settings/{tenantId}:
    get:
      summary: Get tenant settings
      operationId: getSettings
      tags: [Settings]
      security:
        - bearerAuth: []
      parameters:
        - name: tenantId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Tenant settings
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TenantSettings'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden (not tenant admin)
        '404':
          description: Tenant not found

    put:
      summary: Update tenant settings (hotel name and contact info only)
      operationId: updateSettings
      tags: [Settings]
      security:
        - bearerAuth: []
      parameters:
        - name: tenantId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TenantSettingsUpdateInput'
      responses:
        '200':
          description: Settings updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TenantSettings'
        '400':
          description: Validation error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden (not tenant admin)
        '404':
          description: Tenant not found

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT

  schemas:
    TenantSettings:
      type: object
      required:
        - id
        - hotel_name
        - contact_email
        - contact_phone
        - billing_info
      properties:
        id:
          type: string
          format: uuid
        hotel_name:
          type: string
          minLength: 2
          maxLength: 100
          example: 'Grand Hotel'
        contact_email:
          type: string
          format: email
          nullable: true
          example: 'contact@grandhotel.com'
        contact_phone:
          type: string
          nullable: true
          example: '+1-555-123-4567'
        billing_info:
          $ref: '#/components/schemas/BillingInfo'
          nullable: true

    TenantSettingsUpdateInput:
      type: object
      properties:
        hotel_name:
          type: string
          minLength: 2
          maxLength: 100
        contact_email:
          type: string
          format: email
          nullable: true
        contact_phone:
          type: string
          nullable: true

    BillingInfo:
      type: object
      required:
        - plan_name
        - renewal_date
        - payment_method
      properties:
        plan_name:
          type: string
          example: 'Pro'
          description: Current subscription plan
        renewal_date:
          type: string
          format: date
          example: '2025-11-07'
          description: Next billing date
        payment_method:
          type: string
          example: 'Visa •••• 1234'
          description: Payment method on file

    Error:
      type: object
      required:
        - message
      properties:
        message:
          type: string
        errors:
          type: array
          items:
            type: object
            properties:
              field:
                type: string
              message:
                type: string
