# Netlify Configuration for ShareHub Frontend
# https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  # Build command runs from project root
  command = "cd frontend && npm run build"

  # Note: No base or publish directory needed - @netlify/plugin-nextjs handles this automatically

[build.environment]
  # Node version
  NODE_VERSION = "20"

  # Next.js specific
  NEXT_TELEMETRY_DISABLED = "1"

# Next.js Plugin for automatic optimization
[[plugins]]
  package = "@netlify/plugin-nextjs"

# Headers for security and performance
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Cache static assets
[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# ============================================================================
# Scheduled Functions Configuration
# ============================================================================
# Feature 008: R2 Storage - Automated cleanup of expired slides
# NOTE: Scheduled functions are configured in Netlify Dashboard UI, not here
# 1. Go to Netlify Dashboard → Site → Functions
# 2. Select the cleanup function
# 3. Add schedule: "0 */6 * * *" (every 6 hours)
# 4. Or use: netlify functions:schedule api-cleanup "0 */6 * * *"

# Feature 009: CloudConvert Thumbnail Generation - Retroactive generation
# This function generates thumbnails for existing slides without them
# Schedule: "0 2 * * *" (daily at 2:00 AM UTC)
# Configuration steps:
# 1. Go to Netlify Dashboard → Site → Functions
# 2. Select the scheduled-thumbnail-generation function
# 3. Add schedule: "0 2 * * *" (daily at 2:00 AM UTC)
# 4. Or use: netlify functions:schedule scheduled-thumbnail-generation "0 2 * * *"

# ============================================================================
# Environment Variables Configuration Template
# ============================================================================
# Set these in Netlify Dashboard → Site Settings → Environment Variables

# Supabase Configuration
# - NEXT_PUBLIC_SUPABASE_URL          # Your Supabase project URL
# - NEXT_PUBLIC_SUPABASE_ANON_KEY     # Supabase anonymous key (public)
# - SUPABASE_SERVICE_ROLE_KEY         # Supabase service role key (secret, for cleanup function)

# Cloudflare R2 Configuration (Feature 008)
# - R2_ACCOUNT_ID                     # Cloudflare account ID
# - R2_ACCESS_KEY_ID                  # R2 access key ID (secret)
# - R2_SECRET_ACCESS_KEY              # R2 secret access key (secret)
# - R2_BUCKET_NAME                    # R2 bucket name (default: sharehub-slides)

# Legacy Backend (to be removed after Phase 3.9)
# - NEXT_PUBLIC_API_URL               # URL of deployed backend (deprecated)
