# Fly.io configuration for ShareHub Backend
# See https://fly.io/docs/reference/configuration/ for full reference

app = "sharehub-backend"
primary_region = "ams" # Amsterdam - closest to Italy

[build]
  # Use Dockerfile in backend directory
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  NODE_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = "off"
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.checks]]
    grace_period = "10s"
    interval = "30s"
    method = "GET"
    timeout = "5s"
    path = "/health"

# Persistent volume for file storage
# Holds: event files (7 days) + temporary ZIPs (1 day)
# Max ~30 events/week × 500MB = 15GB
[mounts]
  source = "sharehub_storage"
  destination = "/data"
  initial_size = "15gb"

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024  # 1GB RAM for ZIP generation of large files
